### ISSUE TITLE
`ppm run lint` not working

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/remix-server#2]
It looks like the linter is not linting anything:
<img width="683" alt="Screenshot 2022-10-25 at 19 20 33" src="https://user-images.githubusercontent.com/64152453/197840507-5a4753ec-70c9-42e7-b719-ca1393baf790.png">

**Comment by dsod** [comment]
Hey, thanks for opening an issue!
I've added linting commands to relevant packages in 48ae16462b9efa5e650e5055eed4fbb85d2243e7
