### ISSUE TITLE
How can I deploy to Vercel?

### ISSUE THREAD

**Issue by yulafezmesi** [payloadcms/remix-server#5]
Hi, thank you for the great boilerplate!

I've tried to deploy Vercel according to the below building configs. however, the build progress never ends, and no errors. is there any mistake over here?

<img width="925" alt="image" src="https://user-images.githubusercontent.com/45617686/204128002-2276cc7d-83fa-4e75-bf7a-46ffc3231aeb.png">

vercel config:

```javascript
"settings": {
    "createdAt": 1669534729223,
    "framework": null,
    "devCommand": null,
    "installCommand": "pnpm install",
    "buildCommand": "pnpm build && pnpm serve",
    "outputDirectory": "apps/server/dist",
    "rootDirectory": null,
    "directoryListing": false,
    "nodeVersion": "18.x"
  }
```

**Comment by dsod** [comment]
Hi!
Glad you like it.

I believe the `settings.buildCommand` should be: `pnpm build`.

I think you will have a few issues beyond that point though. The project is set up to have Remix and Payload run on the same express server, which lives in the `apps/server` folder. While I have not deployed to vercel myself, I would try this approach: https://vercel.com/guides/using-express-with-vercel#standalone-express. It looks like they support `express.static` which the project use to serve the actual Payload admin UI, and more.

**Comment by dsod** [comment]
After giving Vercel a try my conclusion is that the structure of the project and loading payload as a single file (both the express server and payload config) isn't really a good fit.
