### ISSUE TITLE
[nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by janogale** [payloadcms/remix-server#6]
Thank you @dsod for setting up this amazing template, which combines two of my favorites. 

when I try to run the dev server, I got this error message, see below attached screenshot. 

<img width="603" alt="image" src="https://user-images.githubusercontent.com/45191580/206177209-058cb634-9501-4764-8d7b-84c33a0ebe84.png">

**Comment by dsod** [comment]
Hey, thanks! glad you like it.

Looks like you activated `strict: true` in your `tsconfig.json`. I'll have a look at this in a day or two. Meanwhile you can run without strict mode or excluding the `apps/server/index.ts` from type checking.

**Comment by dsod** [comment]
Fixed in 118264963a30ce2d73a483622e50a5b0f7e254a8
