### ISSUE TITLE
The path "@org/ui" is imported in app/routes/__page.tsx but "@org/ui" was not found in your node_modules. Did you forget to install it?

### ISSUE THREAD

**Issue by MoSattler** [payloadcms/remix-server#8]
Following the initial setup as the README defines it

1. Cloning 
2. pnpm install 
3. pnpm dev

**Comment by dsod** [comment]
I don't seem to be able to re-produce this. Could possibly have been an issue with pnpm/hoisting. Did the app throw an exception, or did you just get a notification?
